from sqlalchemy import Column, Integer, String
from ..database import Base

class SiteList1(Base):
    __tablename__ = "site list 1"

    id = Column(Integer, primary_key=True, index=True)
    sr_id = Column("Sr ID", Integer, index=True, nullable=True)
    site_id = Column("Site ID", String, index=True, nullable=True)
    tech_id = Column("Tech ID", String, nullable=True)
    airtel_site_name = Column("Airtel Site Name", String, nullable=True)
    airtel_zone = Column("Airtel Zone", String, nullable=True)
    dist = Column("Dist", String, nullable=True)
    airtel_zone_2 = Column("Airtel Zone.1", String, nullable=True)
    airtel_zone1 = Column("Airtel Zone1", String, nullable=True)
    state = Column("State", String, nullable=True)
    main_toco = Column("Main TOCO", String, nullable=True)
    pay_load_4g = Column("4G - Pay Load", String, nullable=True)
    toco_id = Column("TOCO ID", String, nullable=True)
    toco_site_name = Column("TOCO Site Name", String, nullable=True)
    toco_zone = Column("TOCO Zone", String, nullable=True)
    site_type = Column("Site Type", String, nullable=True)
    no_of_link = Column("No of Link", String, nullable=True)
    tech = Column("Tech", String, nullable=True)
    oss_2g = Column("OSS-2G", String, nullable=True)
    bsc = Column("BSC", String, nullable=True)
    bcf_no = Column("BCF No", String, nullable=True)
    actual_bcf_name = Column("Actual BCF Name", String, nullable=True)
    in_oss = Column("In OSS", String, nullable=True)
    in_oss_alt = Column("In-OSS", String, nullable=True)
    oss_fd = Column("OSS-FD", String, nullable=True)
    lnbts = Column("LNBTS", String, nullable=True)
    correct_ln_name = Column("Correct LN Name", String, nullable=True)
    ip = Column("IP", String, nullable=True)
    oss_l900 = Column("OSS-L900", String, nullable=True)
    lnbts1 = Column("LNBTS1", String, nullable=True)
    current_ln_name = Column("Current LN Name", String, nullable=True)
    ip1 = Column("IP1", String, nullable=True)
    bss1_name = Column("BSS1 Name", String, nullable=True)
    bss1_no = Column("BSS1 No", String, nullable=True)
    bss2_name = Column("BSS2 Name", String, nullable=True)
    bss2_no = Column("BSS2 No", String, nullable=True)
    ztm_name = Column("ZTM Name", String, nullable=True)
    ztm_no = Column("ZTM No", String, nullable=True)
    tower_type = Column("Tower Type", String, nullable=True)
    bil_cluster = Column("BIL Cluster", String, nullable=True)
    bil_zone = Column("BIL Zone", String, nullable=True)
    bil_hub = Column("BIL Hub", String, nullable=True)
    technician_name = Column("Technician Name", String, nullable=True)
    technician_no = Column("Technician No", String, nullable=True)
    ci_name = Column("CI Name", String, nullable=True)
    ci_no = Column("CI No", String, nullable=True)
    cem = Column("CEM", String, nullable=True)
    zom_name = Column("ZOM Name", String, nullable=True)
    zom_no = Column("ZOM No", String, nullable=True)
    dg_non_dg = Column("DG/Non DG", String, nullable=True)
    non_dg_type = Column("Non DG Type", String, nullable=True)
    eb_non_eb = Column("EB/Non-EB", String, nullable=True)
    eb_status = Column("EB Status", String, nullable=True)
    solar_non_solar = Column("Solar/Non-Solar", String, nullable=True)
    vendor = Column("Vendor", String, nullable=True)
    rfs_date = Column("RFS Date", String, nullable=True)
    shared = Column("Shared", String, nullable=True)
    no_of_cell_2g = Column("No of Cell 2G", String, nullable=True)
    dhq_ndhq = Column("DHQ/NDHQ", String, nullable=True)
    address = Column("Address", String, nullable=True)
    tower_area = Column("Tower Area", String, nullable=True)
    id_od = Column("ID/OD", String, nullable=True)
    rfs_month = Column("RFS Month", String, nullable=True)
    locator_id = Column("Locator ID", String, nullable=True)
    lat = Column("Lat", String, nullable=True)
    long = Column("Long", String, nullable=True)
    dependency = Column("Dependency", String, nullable=True)
    ms_avg_churn = Column("MS-Avg Churn", String, nullable=True)
    opex_cost = Column("Opex Cost", String, nullable=True)
    ubr_ftth = Column("UBR/FTTH", String, nullable=True)
    district = Column("District", String, nullable=True)
    district_2 = Column("District.1", String, nullable=True)
    lt_ht = Column("LT/HT", String, nullable=True)
    pay_load_5g = Column("Pay Load - 5G", String, nullable=True)
    available_5g = Column("5G Available status", String, nullable=True)
    enode_b = Column("Enode-B", String, nullable=True)
    site_id_2 = Column("Site ID.1", String, nullable=True)
    site_id_3 = Column("Site ID 3", String, nullable=True)
